/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetStudentsResponse as EducationApplicationUseCasesStudentsGetStudentsQueryGetStudentsResponse } from '../../models/Education/Application/UseCases/Students/GetStudentsQuery/get-students-response';

export interface ApiStudentsGetStudentsGet$Plain$Params {
  SearchTerm?: string;
  pageNumber?: number;
  pageSize?: number;
  OrderBy?: string;
  IsDecending?: boolean;
}

export function apiStudentsGetStudentsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiStudentsGetStudentsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesStudentsGetStudentsQueryGetStudentsResponse>> {
  const rb = new RequestBuilder(rootUrl, apiStudentsGetStudentsGet$Plain.PATH, 'get');
  if (params) {
    rb.query('SearchTerm', params.SearchTerm, {});
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('OrderBy', params.OrderBy, {});
    rb.query('IsDecending', params.IsDecending, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesStudentsGetStudentsQueryGetStudentsResponse>;
    })
  );
}

apiStudentsGetStudentsGet$Plain.PATH = '/api/Students/GetStudents';
