/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetStudentResponse as EducationApplicationUseCasesStudentsGetStudentQueryGetStudentResponse } from '../../models/Education/Application/UseCases/Students/GetStudentQuery/get-student-response';

export interface ApiStudentsGetStudentGet$Plain$Params {
  Id: string;
}

export function apiStudentsGetStudentGet$Plain(http: HttpClient, rootUrl: string, params: ApiStudentsGetStudentGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesStudentsGetStudentQueryGetStudentResponse>> {
  const rb = new RequestBuilder(rootUrl, apiStudentsGetStudentGet$Plain.PATH, 'get');
  if (params) {
    rb.query('Id', params.Id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesStudentsGetStudentQueryGetStudentResponse>;
    })
  );
}

apiStudentsGetStudentGet$Plain.PATH = '/api/Students/GetStudent';
