/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateOwnLogoCollegeResponse as EducationApplicationUseCasesCollegesUpdateOwnLogoCollegeCommandUpdateOwnLogoCollegeResponse } from '../../models/Education/Application/UseCases/Colleges/UpdateOwnLogoCollegeCommand/update-own-logo-college-response';

export interface ApiCollegesUpdateLogoCollegePatch$Params {
      body?: {
'LogoImage'?: Blob;
}
}

export function apiCollegesUpdateLogoCollegePatch(http: HttpClient, rootUrl: string, params?: ApiCollegesUpdateLogoCollegePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCollegesUpdateOwnLogoCollegeCommandUpdateOwnLogoCollegeResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollegesUpdateLogoCollegePatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCollegesUpdateOwnLogoCollegeCommandUpdateOwnLogoCollegeResponse>;
    })
  );
}

apiCollegesUpdateLogoCollegePatch.PATH = '/api/Colleges/UpdateLogoCollege';
