/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateOwnBannerCollegeResponse as EducationApplicationUseCasesCollegesUpdateOwnBannerCollegeCommandUpdateOwnBannerCollegeResponse } from '../../models/Education/Application/UseCases/Colleges/UpdateOwnBannerCollegeCommand/update-own-banner-college-response';

export interface ApiCollegesUpdateBannerCollegePatch$Plain$Params {
      body?: {
'BannerImage'?: Blob;
}
}

export function apiCollegesUpdateBannerCollegePatch$Plain(http: HttpClient, rootUrl: string, params?: ApiCollegesUpdateBannerCollegePatch$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCollegesUpdateOwnBannerCollegeCommandUpdateOwnBannerCollegeResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollegesUpdateBannerCollegePatch$Plain.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCollegesUpdateOwnBannerCollegeCommandUpdateOwnBannerCollegeResponse>;
    })
  );
}

apiCollegesUpdateBannerCollegePatch$Plain.PATH = '/api/Colleges/UpdateBannerCollege';
