/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCollegesResponse as EducationApplicationUseCasesCollegesCreateCollegesCommandCreateCollegesResponse } from '../../models/Education/Application/UseCases/Colleges/CreateCollegesCommand/create-colleges-response';

export interface ApiCollegesImportCollegesPost$Params {
      body?: {
'CollegesExcel'?: Blob;
'ImagesZip'?: Blob;
}
}

export function apiCollegesImportCollegesPost(http: HttpClient, rootUrl: string, params?: ApiCollegesImportCollegesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCollegesCreateCollegesCommandCreateCollegesResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollegesImportCollegesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCollegesCreateCollegesCommandCreateCollegesResponse>;
    })
  );
}

apiCollegesImportCollegesPost.PATH = '/api/Colleges/ImportColleges';
