/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetCollegesResponse as EducationApplicationUseCasesCollegesGetCollegesQueryGetCollegesResponse } from '../../models/Education/Application/UseCases/Colleges/GetCollegesQuery/get-colleges-response';

export interface ApiCollegesGetCollegesGet$Params {
  SearchTerm?: string | null;
  pageNumber?: number | null;
  pageSize?: number | null;
  OrderBy?: string | null;
  IsDecending?: boolean;
}

export function apiCollegesGetCollegesGet(http: HttpClient, rootUrl: string, params?: ApiCollegesGetCollegesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCollegesGetCollegesQueryGetCollegesResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollegesGetCollegesGet.PATH, 'get');
  if (params) {
    rb.query('SearchTerm', params.SearchTerm, {});
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('OrderBy', params.OrderBy, {});
    rb.query('IsDecending', params.IsDecending, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCollegesGetCollegesQueryGetCollegesResponse>;
    })
  );
}

apiCollegesGetCollegesGet.PATH = '/api/Colleges/GetColleges';
