/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetOwnCollegeResponse as EducationApplicationUseCasesCollegesGetOwnCollegeQueryGetOwnCollegeResponse } from '../../models/Education/Application/UseCases/Colleges/GetOwnCollegeQuery/get-own-college-response';

export interface ApiCollegesGetOwnCollegeGet$Plain$Params {
}

export function apiCollegesGetOwnCollegeGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCollegesGetOwnCollegeGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCollegesGetOwnCollegeQueryGetOwnCollegeResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollegesGetOwnCollegeGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCollegesGetOwnCollegeQueryGetOwnCollegeResponse>;
    })
  );
}

apiCollegesGetOwnCollegeGet$Plain.PATH = '/api/Colleges/GetOwnCollege';
