/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateCollegeCommand as EducationApplicationUseCasesCollegesUpdateCollegeCommandUpdateCollegeCommand } from '../../models/Education/Application/UseCases/Colleges/UpdateCollegeCommand/update-college-command';
import { UpdateCollegeResponse as EducationApplicationUseCasesCollegesUpdateCollegeCommandUpdateCollegeResponse } from '../../models/Education/Application/UseCases/Colleges/UpdateCollegeCommand/update-college-response';

export interface ApiCollegesUpdateCollegePut$Plain$Params {
      body?: EducationApplicationUseCasesCollegesUpdateCollegeCommandUpdateCollegeCommand
}

export function apiCollegesUpdateCollegePut$Plain(http: HttpClient, rootUrl: string, params?: ApiCollegesUpdateCollegePut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCollegesUpdateCollegeCommandUpdateCollegeResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollegesUpdateCollegePut$Plain.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCollegesUpdateCollegeCommandUpdateCollegeResponse>;
    })
  );
}

apiCollegesUpdateCollegePut$Plain.PATH = '/api/Colleges/UpdateCollege';
