/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCourseCommand {
  code?: string | null;
  id?: string;
  title?: string | null;
}
