/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCollegeCommand {
  address?: string | null;
  description?: string | null;
  id?: string;
  name?: string | null;
  phoneNumber?: string | null;
  webAddress?: string | null;
}
