/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FailedRecord as EducationApplicationUseCasesUniversitiesCreateUniversitiesCommandFailedRecord } from '../../../../../../models/Education/Application/UseCases/Universities/CreateUniversitiesCommand/failed-record';
export interface CreateUniversitiesResponse {
  failedRecords?: number;
  failedRecordsDetails?: Array<EducationApplicationUseCasesUniversitiesCreateUniversitiesCommandFailedRecord> | null;
  message?: string | null;
  totalRecords?: number;
  validRecords?: number;
}
