/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FailedRecord as EducationApplicationUseCasesCollegesCreateCollegesCommandFailedRecord } from '../../../../../../models/Education/Application/UseCases/Colleges/CreateCollegesCommand/failed-record';
export interface CreateCollegesResponse {
  failedRecords?: number;
  failedRecordsDetails?: Array<EducationApplicationUseCasesCollegesCreateCollegesCommandFailedRecord> | null;
  message?: string | null;
  totalRecords?: number;
  validRecords?: number;
}
