/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAccountsGetProfilePost } from '../fn/account/api-accounts-get-profile-post';
import { ApiAccountsGetProfilePost$Params } from '../fn/account/api-accounts-get-profile-post';
import { apiAccountsGetProfilePost$Plain } from '../fn/account/api-accounts-get-profile-post-plain';
import { ApiAccountsGetProfilePost$Plain$Params } from '../fn/account/api-accounts-get-profile-post-plain';
import { GetProfileResponse as EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse } from '../models/Education/Application/UseCases/Profiles/GetProfileQuery/get-profile-response';

@Injectable({ providedIn: 'root' })
export class AccountService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAccountsGetProfilePost()` */
  static readonly ApiAccountsGetProfilePostPath = '/api/Accounts/get-profile';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAccountsGetProfilePost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAccountsGetProfilePost$Plain$Response(params?: ApiAccountsGetProfilePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse>> {
    return apiAccountsGetProfilePost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAccountsGetProfilePost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAccountsGetProfilePost$Plain(params?: ApiAccountsGetProfilePost$Plain$Params, context?: HttpContext): Observable<EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse> {
    return this.apiAccountsGetProfilePost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse>): EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAccountsGetProfilePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAccountsGetProfilePost$Response(params?: ApiAccountsGetProfilePost$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse>> {
    return apiAccountsGetProfilePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAccountsGetProfilePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAccountsGetProfilePost(params?: ApiAccountsGetProfilePost$Params, context?: HttpContext): Observable<EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse> {
    return this.apiAccountsGetProfilePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse>): EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse => r.body)
    );
  }

}
