/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CollegePublicDto as EducationApplicationUseCasesProfessorsGetProfessorQueryCollegePublicDto } from '../../../../../../models/Education/Application/UseCases/Professors/GetProfessorQuery/college-public-dto';
export interface GetProfessorResponse {
  college?: EducationApplicationUseCasesProfessorsGetProfessorQueryCollegePublicDto | null;
  email?: string | null;
  id?: string | null;
  name?: string | null;
}
