/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUniversityCommand {
  address?: string | null;
  description?: string | null;
  id: string;
  isPaid?: boolean;
  paidUntil?: string | null;
  phoneNumber?: string | null;
  universityName?: string | null;
  webAddress?: string | null;
}
