/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProfessorByCourseResponseDto as EducationApplicationUseCasesProfessorsGetAllProfessorsByCourseQueryProfessorByCourseResponseDto } from '../../../../../../models/Education/Application/UseCases/Professors/GetAllProfessorsByCourseQuery/professor-by-course-response-dto';
export interface GetAllProfessorsByCourseResponse {
  professors?: Array<EducationApplicationUseCasesProfessorsGetAllProfessorsByCourseQueryProfessorByCourseResponseDto> | null;
}
