/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfessorByCourseResponseDto {
  email?: string | null;
  name?: string | null;
  professorCourseId?: string;
}
