/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AllStudentDto as EducationApplicationDtosAllStudentDto } from '../../../../../../models/Education/Application/Dtos/all-student-dto';
export interface GetStudentsResponse {
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  items?: Array<EducationApplicationDtosAllStudentDto> | null;
  pageNumber?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
}
