/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UniveristyPublicDto as EducationApplicationUseCasesUniversitiesGetUniversitiesQueryUniveristyPublicDto } from '../../../../../../models/Education/Application/UseCases/Universities/GetUniversitiesQuery/univeristy-public-dto';
export interface GetUniversitiesResponse {
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  items?: Array<EducationApplicationUseCasesUniversitiesGetUniversitiesQueryUniveristyPublicDto> | null;
  pageNumber?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
}
