/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileResourceCleanDto as EducationApplicationDtosFileResourceCleanDto } from '../../../../../../models/Education/Application/Dtos/file-resource-clean-dto';
import { CollegesPublicDto as EducationApplicationUseCasesUniversitiesGetUniversitiesQueryCollegesPublicDto } from '../../../../../../models/Education/Application/UseCases/Universities/GetUniversitiesQuery/colleges-public-dto';
export interface UniveristyPublicDto {
  address?: string | null;
  bannerImage?: EducationApplicationDtosFileResourceCleanDto | null;
  colleges?: Array<EducationApplicationUseCasesUniversitiesGetUniversitiesQueryCollegesPublicDto> | null;
  description?: string | null;
  email?: string | null;
  id?: string;
  isPaid?: boolean | null;
  logoImage?: EducationApplicationDtosFileResourceCleanDto | null;
  name?: string | null;
  paidUntil?: string | null;
  phoneNumber?: string | null;
  webAddress?: string | null;
}
