/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FailedRecord as EducationApplicationUseCasesCoursesCreateCoursesCommandFailedRecord } from '../../../../../../models/Education/Application/UseCases/Courses/CreateCoursesCommand/failed-record';
export interface CreateCoursesResponse {
  failedRecords?: number;
  failedRecordsDetails?: Array<EducationApplicationUseCasesCoursesCreateCoursesCommandFailedRecord> | null;
  message?: string | null;
  totalRecords?: number;
  validRecords?: number;
}
