/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetOwnUniversityResponse as EducationApplicationUseCasesUniversitiesGetOwnUniversityQueryGetOwnUniversityResponse } from '../../models/Education/Application/UseCases/Universities/GetOwnUniversityQuery/get-own-university-response';

export interface ApiUniversitiesGetOwnUniversityGet$Plain$Params {
}

export function apiUniversitiesGetOwnUniversityGet$Plain(http: HttpClient, rootUrl: string, params?: ApiUniversitiesGetOwnUniversityGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesUniversitiesGetOwnUniversityQueryGetOwnUniversityResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUniversitiesGetOwnUniversityGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesUniversitiesGetOwnUniversityQueryGetOwnUniversityResponse>;
    })
  );
}

apiUniversitiesGetOwnUniversityGet$Plain.PATH = '/api/Universities/GetOwnUniversity';
