/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateUniversitiesResponse as EducationApplicationUseCasesUniversitiesCreateUniversitiesCommandCreateUniversitiesResponse } from '../../models/Education/Application/UseCases/Universities/CreateUniversitiesCommand/create-universities-response';

export interface ApiUniversitiesImportUniversitiesPost$Params {
      body?: {
'UniversitiesExcel'?: Blob;
'ImagesZip'?: Blob;
}
}

export function apiUniversitiesImportUniversitiesPost(http: HttpClient, rootUrl: string, params?: ApiUniversitiesImportUniversitiesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesUniversitiesCreateUniversitiesCommandCreateUniversitiesResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUniversitiesImportUniversitiesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesUniversitiesCreateUniversitiesCommandCreateUniversitiesResponse>;
    })
  );
}

apiUniversitiesImportUniversitiesPost.PATH = '/api/Universities/ImportUniversities';
