/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetUniversityResponse as EducationApplicationUseCasesUniversitiesGetUniversityQueryGetUniversityResponse } from '../../models/Education/Application/UseCases/Universities/GetUniversityQuery/get-university-response';

export interface ApiUniversitiesGetUniversityGet$Params {
  Id: string;
}

export function apiUniversitiesGetUniversityGet(http: HttpClient, rootUrl: string, params: ApiUniversitiesGetUniversityGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesUniversitiesGetUniversityQueryGetUniversityResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUniversitiesGetUniversityGet.PATH, 'get');
  if (params) {
    rb.query('Id', params.Id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesUniversitiesGetUniversityQueryGetUniversityResponse>;
    })
  );
}

apiUniversitiesGetUniversityGet.PATH = '/api/Universities/GetUniversity';
