/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateOwnBannerUniversityResponse as EducationApplicationUseCasesUniversitiesUpdateOwnBannerUniversityCommandUpdateOwnBannerUniversityResponse } from '../../models/Education/Application/UseCases/Universities/UpdateOwnBannerUniversityCommand/update-own-banner-university-response';

export interface ApiUniversitiesUpdateBannerUniversityPatch$Params {
      body?: {
'BannerImage'?: Blob;
}
}

export function apiUniversitiesUpdateBannerUniversityPatch(http: HttpClient, rootUrl: string, params?: ApiUniversitiesUpdateBannerUniversityPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesUniversitiesUpdateOwnBannerUniversityCommandUpdateOwnBannerUniversityResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUniversitiesUpdateBannerUniversityPatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesUniversitiesUpdateOwnBannerUniversityCommandUpdateOwnBannerUniversityResponse>;
    })
  );
}

apiUniversitiesUpdateBannerUniversityPatch.PATH = '/api/Universities/UpdateBannerUniversity';
