/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetUniversitiesResponse as EducationApplicationUseCasesUniversitiesGetUniversitiesQueryGetUniversitiesResponse } from '../../models/Education/Application/UseCases/Universities/GetUniversitiesQuery/get-universities-response';

export interface ApiUniversitiesGetUniversitiesGet$Plain$Params {
  SearchTerm?: string | null;
  pageNumber?: number | null;
  pageSize?: number | null;
  OrderBy?: string | null;
  IsDecending?: boolean;
}

export function apiUniversitiesGetUniversitiesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiUniversitiesGetUniversitiesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesUniversitiesGetUniversitiesQueryGetUniversitiesResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUniversitiesGetUniversitiesGet$Plain.PATH, 'get');
  if (params) {
    rb.query('SearchTerm', params.SearchTerm, {});
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('OrderBy', params.OrderBy, {});
    rb.query('IsDecending', params.IsDecending, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesUniversitiesGetUniversitiesQueryGetUniversitiesResponse>;
    })
  );
}

apiUniversitiesGetUniversitiesGet$Plain.PATH = '/api/Universities/GetUniversities';
