/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateOwnUniversityCommand as EducationApplicationUseCasesUniversitiesUpdateOwnUniversityCommandUpdateOwnUniversityCommand } from '../../models/Education/Application/UseCases/Universities/UpdateOwnUniversityCommand/update-own-university-command';
import { UpdateOwnUniversityResponse as EducationApplicationUseCasesUniversitiesUpdateOwnUniversityCommandUpdateOwnUniversityResponse } from '../../models/Education/Application/UseCases/Universities/UpdateOwnUniversityCommand/update-own-university-response';

export interface ApiUniversitiesUpdateOwnUniversityPatch$Params {
      body?: EducationApplicationUseCasesUniversitiesUpdateOwnUniversityCommandUpdateOwnUniversityCommand
}

export function apiUniversitiesUpdateOwnUniversityPatch(http: HttpClient, rootUrl: string, params?: ApiUniversitiesUpdateOwnUniversityPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesUniversitiesUpdateOwnUniversityCommandUpdateOwnUniversityResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUniversitiesUpdateOwnUniversityPatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesUniversitiesUpdateOwnUniversityCommandUpdateOwnUniversityResponse>;
    })
  );
}

apiUniversitiesUpdateOwnUniversityPatch.PATH = '/api/Universities/UpdateOwnUniversity';
