/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateUniversityCommand as EducationApplicationUseCasesUniversitiesUpdateUniversityCommandUpdateUniversityCommand } from '../../models/Education/Application/UseCases/Universities/UpdateUniversityCommand/update-university-command';
import { UpdateUniversityResponse as EducationApplicationUseCasesUniversitiesUpdateUniversityCommandUpdateUniversityResponse } from '../../models/Education/Application/UseCases/Universities/UpdateUniversityCommand/update-university-response';

export interface ApiUniversitiesUpdateUniversityPut$Params {
      body?: EducationApplicationUseCasesUniversitiesUpdateUniversityCommandUpdateUniversityCommand
}

export function apiUniversitiesUpdateUniversityPut(http: HttpClient, rootUrl: string, params?: ApiUniversitiesUpdateUniversityPut$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesUniversitiesUpdateUniversityCommandUpdateUniversityResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUniversitiesUpdateUniversityPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesUniversitiesUpdateUniversityCommandUpdateUniversityResponse>;
    })
  );
}

apiUniversitiesUpdateUniversityPut.PATH = '/api/Universities/UpdateUniversity';
