/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetTemplateQuery {
  type?: 'University' | 'College' | 'Student' | 'Course' | 'Professor';
}
