/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RequestOtpCommand as EducationApplicationUseCasesAuthRequestOtpCommandRequestOtpCommand } from '../../models/Education/Application/UseCases/Auth/RequestOtpCommand/request-otp-command';

export interface ApiAuthForgotPasswordRequestResetPasswordOtpPost$Params {
      body?: EducationApplicationUseCasesAuthRequestOtpCommandRequestOtpCommand
}

export function apiAuthForgotPasswordRequestResetPasswordOtpPost(http: HttpClient, rootUrl: string, params?: ApiAuthForgotPasswordRequestResetPasswordOtpPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiAuthForgotPasswordRequestResetPasswordOtpPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiAuthForgotPasswordRequestResetPasswordOtpPost.PATH = '/api/Auth/forgot-password/request-reset-password-otp';
