/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ValidateOtpCommand as EducationApplicationUseCasesAuthValidateOtpCommandValidateOtpCommand } from '../../models/Education/Application/UseCases/Auth/ValidateOtpCommand/validate-otp-command';
import { ValidateOtpResponse as EducationApplicationUseCasesAuthValidateOtpCommandValidateOtpResponse } from '../../models/Education/Application/UseCases/Auth/ValidateOtpCommand/validate-otp-response';

export interface ApiAuthForgotPasswordValidateResetPasswordOtpPost$Plain$Params {
      body?: EducationApplicationUseCasesAuthValidateOtpCommandValidateOtpCommand
}

export function apiAuthForgotPasswordValidateResetPasswordOtpPost$Plain(http: HttpClient, rootUrl: string, params?: ApiAuthForgotPasswordValidateResetPasswordOtpPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesAuthValidateOtpCommandValidateOtpResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthForgotPasswordValidateResetPasswordOtpPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesAuthValidateOtpCommandValidateOtpResponse>;
    })
  );
}

apiAuthForgotPasswordValidateResetPasswordOtpPost$Plain.PATH = '/api/Auth/forgot-password/validate-reset-password-otp';
