/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResetPasswordCommand as EducationApplicationUseCasesAuthResetPasswordCommandResetPasswordCommand } from '../../models/Education/Application/UseCases/Auth/ResetPasswordCommand/reset-password-command';
import { ResetPasswordResponse as EducationApplicationUseCasesAuthResetPasswordCommandResetPasswordResponse } from '../../models/Education/Application/UseCases/Auth/ResetPasswordCommand/reset-password-response';

export interface ApiAuthForgotPasswordResetPasswordPost$Plain$Params {
      body?: EducationApplicationUseCasesAuthResetPasswordCommandResetPasswordCommand
}

export function apiAuthForgotPasswordResetPasswordPost$Plain(http: HttpClient, rootUrl: string, params?: ApiAuthForgotPasswordResetPasswordPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesAuthResetPasswordCommandResetPasswordResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthForgotPasswordResetPasswordPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesAuthResetPasswordCommandResetPasswordResponse>;
    })
  );
}

apiAuthForgotPasswordResetPasswordPost$Plain.PATH = '/api/Auth/forgot-password/reset-password';
