/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProfessorCoursesDto as EducationApplicationUseCasesProfessorsGetAllProfessorCoursesQueryProfessorCoursesDto } from '../../../../../../models/Education/Application/UseCases/Professors/GetAllProfessorCoursesQuery/professor-courses-dto';
export interface GetOwnAllProfessorCoursesResponse {
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  items?: Array<EducationApplicationUseCasesProfessorsGetAllProfessorCoursesQueryProfessorCoursesDto> | null;
  pageNumber?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
}
