/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseByCollegeIdResponseDto as EducationApplicationUseCasesCoursesGetAllCoursesQueryCourseByCollegeIdResponseDto } from '../../../../../../models/Education/Application/UseCases/Courses/GetAllCoursesQuery/course-by-college-id-response-dto';
export interface GetAllCoursesResponse {
  courses?: Array<EducationApplicationUseCasesCoursesGetAllCoursesQueryCourseByCollegeIdResponseDto> | null;
}
