/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateOwnBannerCollegeResponse {
  contentType?: string | null;
  fileName?: string | null;
  filePath?: string | null;
  id?: string;
}
