/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CollegeDetailsResponseDto {
  email?: string | null;
  id?: string;
  name?: string | null;
}
