/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetProfileResponse as EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse } from './models/Education/Application/UseCases/Profiles/GetProfileQuery/get-profile-response';
