/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileResourceCleanDto as EducationApplicationDtosFileResourceCleanDto } from '../../../../../../models/Education/Application/Dtos/file-resource-clean-dto';
import { UniversityPublicDto as EducationApplicationUseCasesCollegesGetCollegeQueryUniversityPublicDto } from '../../../../../../models/Education/Application/UseCases/Colleges/GetCollegeQuery/university-public-dto';
export interface GetCollegeResponse {
  address?: string | null;
  bannerImage?: EducationApplicationDtosFileResourceCleanDto | null;
  description?: string | null;
  email?: string | null;
  id?: string;
  logoImage?: EducationApplicationDtosFileResourceCleanDto | null;
  name?: string | null;
  phoneNumber?: string | null;
  university?: EducationApplicationUseCasesCollegesGetCollegeQueryUniversityPublicDto | null;
  webAddress?: string | null;
}
