/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UniversityPublicDto {
  address?: string | null;
  description?: string | null;
  email?: string | null;
  id?: string;
  isPaid?: boolean | null;
  name?: string | null;
  paidUntil?: string | null;
  phoneNumber?: string | null;
  webAddress?: string | null;
}
