/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FailedRecord {
  errors?: Array<string> | null;
  name?: string | null;
  rowNumber?: number;
}
