/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResetPasswordCommand {
  email: string;
  newPassword: any & any & any & any;
  otp: string;
}
