/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetAllCoursesResponse as EducationApplicationUseCasesCoursesGetAllCoursesQueryGetAllCoursesResponse } from '../../models/Education/Application/UseCases/Courses/GetAllCoursesQuery/get-all-courses-response';

export interface ApiCoursesGetAllCoursesGet$Plain$Params {
}

export function apiCoursesGetAllCoursesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCoursesGetAllCoursesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCoursesGetAllCoursesQueryGetAllCoursesResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCoursesGetAllCoursesGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCoursesGetAllCoursesQueryGetAllCoursesResponse>;
    })
  );
}

apiCoursesGetAllCoursesGet$Plain.PATH = '/api/Courses/GetAllCourses';
