/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCourseCommand as EducationApplicationUseCasesCoursesCreateCourseCommandCreateCourseCommand } from '../../models/Education/Application/UseCases/Courses/CreateCourseCommand/create-course-command';
import { CreateCourseResponse as EducationApplicationUseCasesCoursesCreateCourseCommandCreateCourseResponse } from '../../models/Education/Application/UseCases/Courses/CreateCourseCommand/create-course-response';

export interface ApiCoursesCreateCoursePost$Params {
      body?: EducationApplicationUseCasesCoursesCreateCourseCommandCreateCourseCommand
}

export function apiCoursesCreateCoursePost(http: HttpClient, rootUrl: string, params?: ApiCoursesCreateCoursePost$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCoursesCreateCourseCommandCreateCourseResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCoursesCreateCoursePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCoursesCreateCourseCommandCreateCourseResponse>;
    })
  );
}

apiCoursesCreateCoursePost.PATH = '/api/Courses/CreateCourse';
