/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetCourseResponse as EducationApplicationUseCasesCoursesGetCourseQueryGetCourseResponse } from '../../models/Education/Application/UseCases/Courses/GetCourseQuery/get-course-response';

export interface ApiCoursesGetCourseGet$Plain$Params {
  Id?: string;
}

export function apiCoursesGetCourseGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCoursesGetCourseGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCoursesGetCourseQueryGetCourseResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCoursesGetCourseGet$Plain.PATH, 'get');
  if (params) {
    rb.query('Id', params.Id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCoursesGetCourseQueryGetCourseResponse>;
    })
  );
}

apiCoursesGetCourseGet$Plain.PATH = '/api/Courses/GetCourse';
