/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCoursesResponse as EducationApplicationUseCasesCoursesCreateCoursesCommandCreateCoursesResponse } from '../../models/Education/Application/UseCases/Courses/CreateCoursesCommand/create-courses-response';

export interface ApiCoursesImportCoursesPost$Params {
      body?: {
'CoursesExcel'?: Blob;
}
}

export function apiCoursesImportCoursesPost(http: HttpClient, rootUrl: string, params?: ApiCoursesImportCoursesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesCoursesCreateCoursesCommandCreateCoursesResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCoursesImportCoursesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesCoursesCreateCoursesCommandCreateCoursesResponse>;
    })
  );
}

apiCoursesImportCoursesPost.PATH = '/api/Courses/ImportCourses';
