/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetTemplateResponse as EducationApplicationUseCasesTemplateGetTemplateResponse } from '../../models/Education/Application/UseCases/Template/get-template-response';

export interface ApiTemplateGetImportTemplateGet$Params {
  Type?: 'University' | 'College' | 'Student' | 'Course' | 'Professor';
}

export function apiTemplateGetImportTemplateGet(http: HttpClient, rootUrl: string, params?: ApiTemplateGetImportTemplateGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesTemplateGetTemplateResponse>> {
  const rb = new RequestBuilder(rootUrl, apiTemplateGetImportTemplateGet.PATH, 'get');
  if (params) {
    rb.query('Type', params.Type, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesTemplateGetTemplateResponse>;
    })
  );
}

apiTemplateGetImportTemplateGet.PATH = '/api/Template/GetImportTemplate';
