/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AllStudentDto {
  collegeId?: string;
  department?: string | null;
  email?: string | null;
  gpa?: number | null;
  id?: string | null;
  major?: string | null;
  name?: string | null;
  studentCollegeId?: string | null;
}
