/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CoursePreDto {
  code?: string | null;
  collegeId?: string;
  id?: string;
  title?: string | null;
}
