/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseProfessorDto as EducationApplicationDtosCourseProfessorDto } from '../../../../models/Education/Application/Dtos/course-professor-dto';
import { ProfessorDto as EducationApplicationDtosProfessorDto } from '../../../../models/Education/Application/Dtos/professor-dto';
export interface ProfessorCourseDto {
  course?: EducationApplicationDtosCourseProfessorDto | null;
  courseId?: string;
  id?: string;
  professor?: EducationApplicationDtosProfessorDto | null;
  professorId?: string | null;
}
