/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StudentSemesterDto as EducationApplicationDtosStudentSemesterDto } from '../../../../models/Education/Application/Dtos/student-semester-dto';
export interface StudentLevelDto {
  id?: string;
  levelNumber?: 'Preparatory' | 'One' | 'Two' | 'Three' | 'Four' | 'Five' | 'Six' | 'Seven' | 'Eight' | 'Nine' | 'Ten';
  semesters?: Array<EducationApplicationDtosStudentSemesterDto> | null;
  studentId?: string | null;
}
