/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProfessorCourseDto as EducationApplicationDtosProfessorCourseDto } from '../../../../models/Education/Application/Dtos/professor-course-dto';
export interface StudentSemesterCourseDto {
  courseGrade?: string | null;
  courseStatus?: 'Ongoing' | 'Completed' | 'Withdraw' | 'Failed';
  id?: string;
  professorCourse?: EducationApplicationDtosProfessorCourseDto | null;
  professorCourseId?: string;
  studentSemesterId?: string;
}
