/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StudentSemesterCourseDto as EducationApplicationDtosStudentSemesterCourseDto } from '../../../../models/Education/Application/Dtos/student-semester-course-dto';
export interface StudentSemesterDto {
  courses?: Array<EducationApplicationDtosStudentSemesterCourseDto> | null;
  id?: string;
  semester?: 'One' | 'Two' | 'Summer';
  studentLevelId?: string;
}
