/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseProfDto as EducationApplicationUseCasesProfessorsGetAllProfessorCoursesQueryCourseProfDto } from '../../../../../../models/Education/Application/UseCases/Professors/GetAllProfessorCoursesQuery/course-prof-dto';
export interface ProfessorCoursesDto {
  course?: EducationApplicationUseCasesProfessorsGetAllProfessorCoursesQueryCourseProfDto | null;
  courseId?: string;
  id?: string;
  isReady?: boolean;
}
