/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProfessorResponse {
  collegeId?: string;
  email?: string | null;
  id?: string | null;
  name?: string | null;
}
