/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StudentLevelCommand as EducationApplicationUseCasesStudentsCreateStudentCommandStudentLevelCommand } from '../../../../../../models/Education/Application/UseCases/Students/CreateStudentCommand/student-level-command';
export interface CreateStudentCommand {
  department?: string | null;
  email: string;
  gpa?: number | null;
  levels: Array<EducationApplicationUseCasesStudentsCreateStudentCommandStudentLevelCommand>;
  major?: string | null;
  name: string;
  studentCollegeId: string;
}
