/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StudentLevelDto as EducationApplicationDtosStudentLevelDto } from '../../../../../../models/Education/Application/Dtos/student-level-dto';
export interface CreateStudentResponse {
  collegeId?: string;
  department?: string | null;
  email?: string | null;
  gpa?: number | null;
  id?: string | null;
  levels?: Array<EducationApplicationDtosStudentLevelDto> | null;
  major?: string | null;
  name?: string | null;
  studentCollegeId?: string | null;
}
