/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentSemesterCourseCommand {
  courseGrade?: string | null;
  courseStatus?: 'Ongoing' | 'Completed' | 'Withdraw' | 'Failed';
  professorCourseId: string;
}
