/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StudentSemesterCourseCommand as EducationApplicationUseCasesStudentsCreateStudentCommandStudentSemesterCourseCommand } from '../../../../../../models/Education/Application/UseCases/Students/CreateStudentCommand/student-semester-course-command';
export interface StudentSemseterCommand {
  courses: Array<EducationApplicationUseCasesStudentsCreateStudentCommandStudentSemesterCourseCommand>;
  semester?: 'One' | 'Two' | 'Summer';
}
