/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StudentSemseterCommand as EducationApplicationUseCasesStudentsCreateStudentCommandStudentSemseterCommand } from '../../../../../../models/Education/Application/UseCases/Students/CreateStudentCommand/student-semseter-command';
export interface StudentLevelCommand {
  levelNumber?: 'Preparatory' | 'One' | 'Two' | 'Three' | 'Four' | 'Five' | 'Six' | 'Seven' | 'Eight' | 'Nine' | 'Ten';
  semesters: Array<EducationApplicationUseCasesStudentsCreateStudentCommandStudentSemseterCommand>;
}
