/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UniversityCollegePublicDto as EducationApplicationUseCasesCollegesGetCollegesQueryUniversityCollegePublicDto } from '../../../../../../models/Education/Application/UseCases/Colleges/GetCollegesQuery/university-college-public-dto';
export interface CollegePuplicDto {
  address?: string | null;
  description?: string | null;
  email?: string | null;
  id?: string;
  name?: string | null;
  phoneNumber?: string | null;
  university?: EducationApplicationUseCasesCollegesGetCollegesQueryUniversityCollegePublicDto | null;
  webAddress?: string | null;
}
