/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CollegePuplicDto as EducationApplicationUseCasesCollegesGetCollegesQueryCollegePuplicDto } from '../../../../../../models/Education/Application/UseCases/Colleges/GetCollegesQuery/college-puplic-dto';
export interface GetCollegesResponse {
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  items?: Array<EducationApplicationUseCasesCollegesGetCollegesQueryCollegePuplicDto> | null;
  pageNumber?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
}
