/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UniversityCollegePublicDto {
  email?: string | null;
  id?: string;
  isPaid?: boolean | null;
  name?: string | null;
  paidUntil?: string | null;
}
