/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CollegesService } from './services/colleges.service';
export { CoursesService } from './services/courses.service';
export { ProfessorsService } from './services/professors.service';
export { StudentsService } from './services/students.service';
export { TemplateService } from './services/template.service';
export { UniversitiesService } from './services/universities.service';
