/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetAllProfessorsByCourseResponse as EducationApplicationUseCasesProfessorsGetAllProfessorsByCourseQueryGetAllProfessorsByCourseResponse } from '../../models/Education/Application/UseCases/Professors/GetAllProfessorsByCourseQuery/get-all-professors-by-course-response';

export interface ApiProfessorsGetAllProfessorByCourseGet$Params {
  CourseId: string;
}

export function apiProfessorsGetAllProfessorByCourseGet(http: HttpClient, rootUrl: string, params: ApiProfessorsGetAllProfessorByCourseGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesProfessorsGetAllProfessorsByCourseQueryGetAllProfessorsByCourseResponse>> {
  const rb = new RequestBuilder(rootUrl, apiProfessorsGetAllProfessorByCourseGet.PATH, 'get');
  if (params) {
    rb.query('CourseId', params.CourseId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesProfessorsGetAllProfessorsByCourseQueryGetAllProfessorsByCourseResponse>;
    })
  );
}

apiProfessorsGetAllProfessorByCourseGet.PATH = '/api/Professors/GetAllProfessorByCourse';
