/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateProfessorCommand as EducationApplicationUseCasesProfessorsCreateProfessorCommandCreateProfessorCommand } from '../../models/Education/Application/UseCases/Professors/CreateProfessorCommand/create-professor-command';
import { CreateProfessorResponse as EducationApplicationUseCasesProfessorsCreateProfessorCommandCreateProfessorResponse } from '../../models/Education/Application/UseCases/Professors/CreateProfessorCommand/create-professor-response';

export interface ApiProfessorsCreateProfessorPost$Plain$Params {
      body?: EducationApplicationUseCasesProfessorsCreateProfessorCommandCreateProfessorCommand
}

export function apiProfessorsCreateProfessorPost$Plain(http: HttpClient, rootUrl: string, params?: ApiProfessorsCreateProfessorPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesProfessorsCreateProfessorCommandCreateProfessorResponse>> {
  const rb = new RequestBuilder(rootUrl, apiProfessorsCreateProfessorPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesProfessorsCreateProfessorCommandCreateProfessorResponse>;
    })
  );
}

apiProfessorsCreateProfessorPost$Plain.PATH = '/api/Professors/CreateProfessor';
