/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetOwnAllProfessorCoursesResponse as EducationApplicationUseCasesProfessorsGetOwnAllProfessorCoursesQueryGetOwnAllProfessorCoursesResponse } from '../../models/Education/Application/UseCases/Professors/GetOwnAllProfessorCoursesQuery/get-own-all-professor-courses-response';

export interface ApiProfessorsGetOwnProfessorCoursesGet$Plain$Params {
  SearchTerm?: string;
  pageNumber?: number;
  pageSize?: number;
  OrderBy?: string;
  IsDecending?: boolean;
}

export function apiProfessorsGetOwnProfessorCoursesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiProfessorsGetOwnProfessorCoursesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesProfessorsGetOwnAllProfessorCoursesQueryGetOwnAllProfessorCoursesResponse>> {
  const rb = new RequestBuilder(rootUrl, apiProfessorsGetOwnProfessorCoursesGet$Plain.PATH, 'get');
  if (params) {
    rb.query('SearchTerm', params.SearchTerm, {});
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('OrderBy', params.OrderBy, {});
    rb.query('IsDecending', params.IsDecending, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesProfessorsGetOwnAllProfessorCoursesQueryGetOwnAllProfessorCoursesResponse>;
    })
  );
}

apiProfessorsGetOwnProfessorCoursesGet$Plain.PATH = '/api/Professors/GetOwnProfessorCourses';
