/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetAllProfessorsResponse as EducationApplicationUseCasesProfessorsGetAllProfessorsQueryGetAllProfessorsResponse } from '../../models/Education/Application/UseCases/Professors/GetAllProfessorsQuery/get-all-professors-response';

export interface ApiProfessorsGetProfessorsGet$Params {
  SearchTerm?: string | null;
  pageNumber?: number | null;
  pageSize?: number | null;
  OrderBy?: string | null;
  IsDecending?: boolean;
}

export function apiProfessorsGetProfessorsGet(http: HttpClient, rootUrl: string, params?: ApiProfessorsGetProfessorsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesProfessorsGetAllProfessorsQueryGetAllProfessorsResponse>> {
  const rb = new RequestBuilder(rootUrl, apiProfessorsGetProfessorsGet.PATH, 'get');
  if (params) {
    rb.query('SearchTerm', params.SearchTerm, {});
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('OrderBy', params.OrderBy, {});
    rb.query('IsDecending', params.IsDecending, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesProfessorsGetAllProfessorsQueryGetAllProfessorsResponse>;
    })
  );
}

apiProfessorsGetProfessorsGet.PATH = '/api/Professors/GetProfessors';
