/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProfessorDto as EducationApplicationUseCasesProfessorsGetAllProfessorsQueryProfessorDto } from '../../../../../../models/Education/Application/UseCases/Professors/GetAllProfessorsQuery/professor-dto';
export interface GetAllProfessorsResponse {
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  items?: Array<EducationApplicationUseCasesProfessorsGetAllProfessorsQueryProfessorDto> | null;
  pageNumber?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
}
