/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CoursePreDto as EducationApplicationDtosCoursePreDto } from '../../../../../../models/Education/Application/Dtos/course-pre-dto';
export interface CreateCourseResponse {
  code?: string | null;
  collegeId?: string;
  id?: string;
  prerequisites?: Array<EducationApplicationDtosCoursePreDto> | null;
  title?: string | null;
}
