/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCourseCommand {
  code: string;
  prerequisiteCourseIds?: Array<string> | null;
  title: string;
}
