/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileResourceCleanDto as EducationApplicationDtosFileResourceCleanDto } from '../../../../../../models/Education/Application/Dtos/file-resource-clean-dto';
export interface CreateUniversityResponse {
  address?: string | null;
  bannerImage?: EducationApplicationDtosFileResourceCleanDto | null;
  description?: string | null;
  email?: string | null;
  id?: string;
  isPaid?: boolean;
  logoImage?: EducationApplicationDtosFileResourceCleanDto | null;
  name?: string | null;
  paidUntil?: string | null;
  phoneNumber?: string | null;
  webAddress?: string | null;
}
