/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LessonDetailsDto as EducationApplicationUseCasesProfessorsGetOwnProfessorCourseQueryLessonDetailsDto } from '../../../../../../models/Education/Application/UseCases/Professors/GetOwnProfessorCourseQuery/lesson-details-dto';
export interface ChapterDetailsDto {
  id?: string;
  lessons?: Array<EducationApplicationUseCasesProfessorsGetOwnProfessorCourseQueryLessonDetailsDto> | null;
  title?: string | null;
}
