/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileResourceCleanDto as EducationApplicationDtosFileResourceCleanDto } from '../../../../../../models/Education/Application/Dtos/file-resource-clean-dto';
import { ChapterDetailsDto as EducationApplicationUseCasesProfessorsGetOwnProfessorCourseQueryChapterDetailsDto } from '../../../../../../models/Education/Application/UseCases/Professors/GetOwnProfessorCourseQuery/chapter-details-dto';
import { CourseDetailsDto as EducationApplicationUseCasesProfessorsGetOwnProfessorCourseQueryCourseDetailsDto } from '../../../../../../models/Education/Application/UseCases/Professors/GetOwnProfessorCourseQuery/course-details-dto';
export interface GetOwnProfessorCourseResponse {
  chapters?: Array<EducationApplicationUseCasesProfessorsGetOwnProfessorCourseQueryChapterDetailsDto> | null;
  course?: EducationApplicationUseCasesProfessorsGetOwnProfessorCourseQueryCourseDetailsDto | null;
  courseId?: string;
  files?: Array<EducationApplicationDtosFileResourceCleanDto> | null;
  id?: string;
  isReady?: boolean;
  professorId?: string | null;
}
