/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetProfileResponse as EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse } from '../../models/Education/Application/UseCases/Profiles/GetProfileQuery/get-profile-response';

export interface ApiAccountsGetProfilePost$Params {
}

export function apiAccountsGetProfilePost(http: HttpClient, rootUrl: string, params?: ApiAccountsGetProfilePost$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAccountsGetProfilePost.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesProfilesGetProfileQueryGetProfileResponse>;
    })
  );
}

apiAccountsGetProfilePost.PATH = '/api/Accounts/get-profile';
