/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetCoursesQuery {
  isDecending?: boolean;
  orderBy?: string | null;
  pageNumber?: number | null;
  pageSize?: number | null;
  searchTerm?: string | null;
}
