/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseResponseDto as EducationApplicationUseCasesCoursesGetCoursesQueryCourseResponseDto } from '../../../../../../models/Education/Application/UseCases/Courses/GetCoursesQuery/course-response-dto';
export interface GetCoursesResponse {
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  items?: Array<EducationApplicationUseCasesCoursesGetCoursesQueryCourseResponseDto> | null;
  pageNumber?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
}
