/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetProfileResponse {
  email?: string | null;
  id?: string | null;
  name?: string | null;
  userRole?: string | null;
}
