/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileResourceCleanDto as EducationApplicationDtosFileResourceCleanDto } from '../../../../../../models/Education/Application/Dtos/file-resource-clean-dto';
import { CollegePublicDto as EducationApplicationUseCasesUniversitiesGetUniversityQueryCollegePublicDto } from '../../../../../../models/Education/Application/UseCases/Universities/GetUniversityQuery/college-public-dto';
export interface GetUniversityResponse {
  address?: string | null;
  bannerImage?: EducationApplicationDtosFileResourceCleanDto | null;
  colleges?: Array<EducationApplicationUseCasesUniversitiesGetUniversityQueryCollegePublicDto> | null;
  description?: string | null;
  email?: string | null;
  id?: string;
  isPaid?: boolean | null;
  logoImage?: EducationApplicationDtosFileResourceCleanDto | null;
  name?: string | null;
  paidUntil?: string | null;
  phoneNumber?: string | null;
  webAddress?: string | null;
}
