/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginReponse {
  email?: string | null;
  expiresOn?: string;
  isAuthenticated?: boolean;
  name?: string | null;
  requiresPasswordReset?: boolean;
  roles?: Array<string> | null;
  token?: string | null;
}
