/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTemplateGetImportTemplateGet } from '../fn/template/api-template-get-import-template-get';
import { ApiTemplateGetImportTemplateGet$Params } from '../fn/template/api-template-get-import-template-get';
import { GetTemplateResponse as EducationApplicationUseCasesTemplateGetTemplateResponse } from '../models/Education/Application/UseCases/Template/get-template-response';

@Injectable({ providedIn: 'root' })
export class TemplateService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTemplateGetImportTemplateGet()` */
  static readonly ApiTemplateGetImportTemplateGetPath = '/api/Template/GetImportTemplate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTemplateGetImportTemplateGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTemplateGetImportTemplateGet$Response(params?: ApiTemplateGetImportTemplateGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesTemplateGetTemplateResponse>> {
    return apiTemplateGetImportTemplateGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTemplateGetImportTemplateGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTemplateGetImportTemplateGet(params?: ApiTemplateGetImportTemplateGet$Params, context?: HttpContext): Observable<EducationApplicationUseCasesTemplateGetTemplateResponse> {
    return this.apiTemplateGetImportTemplateGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<EducationApplicationUseCasesTemplateGetTemplateResponse>): EducationApplicationUseCasesTemplateGetTemplateResponse => r.body)
    );
  }

}
