/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FailedRecord as EducationApplicationUseCasesStudentsCreateStudentsCommandFailedRecord } from '../../../../../../models/Education/Application/UseCases/Students/CreateStudentsCommand/failed-record';
export interface CreateStudentsResponse {
  failedRecords?: number;
  failedRecordsDetails?: Array<EducationApplicationUseCasesStudentsCreateStudentsCommandFailedRecord> | null;
  message?: string | null;
  totalRecords?: number;
  validRecords?: number;
}
