/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { LoginCommand as EducationApplicationUseCasesAuthLoginLoginCommand } from './models/Education/Application/UseCases/Auth/Login/login-command';
export type { LoginReponse as EducationApplicationUseCasesAuthLoginLoginReponse } from './models/Education/Application/UseCases/Auth/Login/login-reponse';
export type { LoginViaMicrosoftResponse as EducationApplicationUseCasesAuthLoginViaMircosoftQueryLoginViaMicrosoftResponse } from './models/Education/Application/UseCases/Auth/LoginViaMircosoftQuery/login-via-microsoft-response';
export type { RequestOtpCommand as EducationApplicationUseCasesAuthRequestOtpCommandRequestOtpCommand } from './models/Education/Application/UseCases/Auth/RequestOtpCommand/request-otp-command';
export type { ResetPasswordCommand as EducationApplicationUseCasesAuthResetPasswordCommandResetPasswordCommand } from './models/Education/Application/UseCases/Auth/ResetPasswordCommand/reset-password-command';
export type { ResetPasswordResponse as EducationApplicationUseCasesAuthResetPasswordCommandResetPasswordResponse } from './models/Education/Application/UseCases/Auth/ResetPasswordCommand/reset-password-response';
export type { ValidateOtpCommand as EducationApplicationUseCasesAuthValidateOtpCommandValidateOtpCommand } from './models/Education/Application/UseCases/Auth/ValidateOtpCommand/validate-otp-command';
export type { ValidateOtpResponse as EducationApplicationUseCasesAuthValidateOtpCommandValidateOtpResponse } from './models/Education/Application/UseCases/Auth/ValidateOtpCommand/validate-otp-response';
