/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginViaMicrosoftResponse as EducationApplicationUseCasesAuthLoginViaMircosoftQueryLoginViaMicrosoftResponse } from '../../models/Education/Application/UseCases/Auth/LoginViaMircosoftQuery/login-via-microsoft-response';

export interface ApiAuthMicrosoftCallbackGet$Plain$Params {
  returnURL?: string;
  remoteError?: string;
}

export function apiAuthMicrosoftCallbackGet$Plain(http: HttpClient, rootUrl: string, params?: ApiAuthMicrosoftCallbackGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesAuthLoginViaMircosoftQueryLoginViaMicrosoftResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthMicrosoftCallbackGet$Plain.PATH, 'get');
  if (params) {
    rb.query('returnURL', params.returnURL, {});
    rb.query('remoteError', params.remoteError, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesAuthLoginViaMircosoftQueryLoginViaMicrosoftResponse>;
    })
  );
}

apiAuthMicrosoftCallbackGet$Plain.PATH = '/api/Auth/microsoft-callback';
