/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginCommand as EducationApplicationUseCasesAuthLoginLoginCommand } from '../../models/Education/Application/UseCases/Auth/Login/login-command';
import { LoginReponse as EducationApplicationUseCasesAuthLoginLoginReponse } from '../../models/Education/Application/UseCases/Auth/Login/login-reponse';

export interface ApiAuthLoginPost$Plain$Params {
      body?: EducationApplicationUseCasesAuthLoginLoginCommand
}

export function apiAuthLoginPost$Plain(http: HttpClient, rootUrl: string, params?: ApiAuthLoginPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EducationApplicationUseCasesAuthLoginLoginReponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthLoginPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EducationApplicationUseCasesAuthLoginLoginReponse>;
    })
  );
}

apiAuthLoginPost$Plain.PATH = '/api/Auth/Login';
